# Generated by Django 5.1.6 on 2025-10-26 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hutulbur', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=20)),
                ('damjaa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('лекц', 'Лекц'), ('лаб', 'Лаб'), ('семинар', 'Семинар')], max_length=20)),
                ('room_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lesson_type', models.CharField(max_length=20)),
                ('available_room_types', models.JSONField(default=list)),
                ('group_list', models.ManyToManyField(to='timeapp.classgroup')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeapp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeapp.course')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeapp.room')),
            ],
        ),
    ]
