# Generated by Django 5.1.6 on 2025-11-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_id',
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='group_list',
            field=models.ManyToManyField(blank=True, to='timeapp.classgroup'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Mon', 'Даваа'), ('Tue', 'Мягмар'), ('Wed', 'Лхагва'), ('Thu', 'Пүрэв'), ('Fri', 'Баасан'), ('Sat', 'Бямба')], max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.CharField(choices=[('08:00-09:30', '08:00-09:30'), ('09:40-11:10', '09:40-11:10'), ('11:20-12:50', '11:20-12:50'), ('13:30-15:00', '13:30-15:00'), ('15:10-16:40', '15:10-16:40')], max_length=20),
        ),
    ]
