# Generated by Django 5.1.6 on 2026-01-17 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0006_teacher_age_teacher_email_teacher_ovog_teacher_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='parent_lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='timeapp.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lesson_type',
            field=models.CharField(choices=[('лекц', 'Лекц'), ('семинар', 'Семинар'), ('лаб', 'Лаб')], max_length=20),
        ),
    ]
