# Generated by Django 5.1.6 on 2026-01-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0007_course_parent_lecture_alter_course_lesson_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='slots_per_week',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='lesson_type',
            field=models.CharField(choices=[('лекц', 'Лекц'), ('семинар', 'Семинар'), ('лаб', 'Лаб'), ('практик', 'Практик')], max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('лекц', 'Лекц'), ('лаб', 'Лаб'), ('семинар', 'Семинар'), ('практик', 'Практик')], max_length=20),
        ),
    ]
