# Generated by Django 5.1.6 on 2026-04-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeapp', '0009_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='days_off',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
